Auth/urls.py
from django.urls import path
from .views import User_login_view,Client_register_view
from Auth import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'auth'

urlpatterns = [
    path('register/',Client_register_view.as_view(),name='register'),
    path('login/',User_login_view.as_view(),name='login'),
    path('logout/',views.logout_request,name='logout'),
]

core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from core import views
from core.views import detailed_info
from core.views import binnacle
from core.views import Project_view
from core.views import Gallery
from core.views import Donation_methods
from core.views import Successful_donation
from core.views import Convocatory_inscription
from core.views import Suggestion_view
app_name = 'core'
base_url_employee = 'ehome/'

urlpatterns = [
    path('donation/<project_id>', views.Stripe_donation.as_view(), name='donation'),
    path('', views.Home_view.as_view(), name='home'),
    path('home/', views.Home_view.as_view(), name='home'),
    path('categories/', views.Categories_view.as_view(), name='categories'),
    path('detailedinfo/', detailed_info.as_view(), name='detailedinfo'),
    path('binnacle/', binnacle.as_view(), name='binnacle'),
    path(base_url_employee, views.Home_view_employee.as_view(), name='employee_home'),
    path('gallery/', Gallery.as_view(), name ='gallery'),
    path('project/', Project_view.as_view(), name ='project'),
    path('donation_methods/', Donation_methods.as_view(), name='donation_methods'),
    path('ehome/categories/',views.Employee_categories.as_view(),name='ecategories'),
    path('ehome/projects/',views.Employee_projects.as_view(),name='eprojects'),
    path('ehome/beneficiaries/',views.Employee_beneficiaries.as_view(),name='ebeneficiaries'),
    path('ehome/beneficiaries/<beneficiary_id>',views.Edit_beneficiaries.as_view(),name='e_edit_beneficiaries'),
    path(base_url_employee+'categories/',views.Employee_categories.as_view(),name='ecategories'),
    path(base_url_employee+'convocatories/',views.Employee_convocatories.as_view(),name='econvocatories'),
    path(base_url_employee+'clients/',views.Employee_clients.as_view(),name='eclients'),
    path(base_url_employee+'tools/',views.Employee_tools.as_view(),name='etools'),
    path(base_url_employee+'categories/edit/<category_id>',views.Edit_category.as_view(),name='edit_category_ehome'),
    path(base_url_employee+'categories/delete/<category_id>',views.Delete_category.delete_category,name='delete_category_ehome'),
    path(base_url_employee+'categories/save',views.Save_Category.as_view(),name='save_category_ehome'),
    path(base_url_employee+'states/',views.Employee_states.as_view(),name='estates'),
    path(base_url_employee+'states/edit/<state_id>',views.Edit_state.as_view(),name='edit_state_ehome'),
    path(base_url_employee+'states/delete/<state_id>',views.Delete_state.delete_state,name='delete_state_ehome'),
    path(base_url_employee+'states/save',views.Save_state.as_view(),name='save_state_ehome'),
    path(base_url_employee+'tools/save',views.Save_employee.as_view(),name='save_employee_ehome'),
    path(base_url_employee+'projects/edit/<project_id>',views.Edit_project.as_view(),name='edit_project_ehome'),
    path(base_url_employee+'projects/save',views.Save_project.as_view(),name='save_project_ehome'),
    path(base_url_employee+'projects/delete/<project_id>',views.Delete_project.delete_project,name='delete_project_ehome'),
    path('convocatory',Convocatory_inscription.as_view(),name='convocatory'),
    path(base_url_employee+'convocatories/save',views.Save_convocatories.as_view(),name='save_convocatory_ehome'),
    path(base_url_employee+'convocatories/edit/<convocatory_id>',views.Edit_convocatory.as_view(),name='edit_convocatory_ehome'),
    path(base_url_employee+'convocatories/delete/<convocatory_id>',views.Delete_convocatory.delete_convocatory,name='delete_convocatory_ehome'),
    path(base_url_employee+'tools/edit/<username>',views.Edit_employee.as_view(),name='edit_employee_ehome'),
    path(base_url_employee+'tools/delete/<username>',views.Delete_employe.delete_employee,name='delete_employee_ehome'),
    path('suggestions/',Suggestion_view.as_view(),name='suggestions'),
]

urlpatterns += staticfiles_urlpatterns()

knowledge_projects/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Auth.urls')),
    path('',include('core.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.utils import timezone
from django.db import models
from Auth.models import User, Client

class State(models.Model):
    state_id=models.AutoField(primary_key=True)
    state_name = models.CharField(max_length=30)
    description = models.TextField()
    def __str__(self):
        return self.state_name

class Category(models.Model):
    category_id=models.AutoField(primary_key=True)
    category_name = models.TextField(max_length=30)
    icon_src = models.TextField(max_length=30)
    description = models.TextField()
    def __str__(self):
        return self.category_name
    

class Convocatory(models.Model):
    #Primary key
    convocatory_id = models.AutoField(primary_key=True)
    convocatory_name = models.CharField(max_length=30)
    start_date = models.DateField()
    closing_date = models.DateField()
    def __str__(self):
        return self.convocatory_name

class Project(models.Model):
    #Primary key
    project_id = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=50)
    project_description = models.TextField()
    result = models.TextField()
    scope = models.TextField()
    work_plan = models.TextField()
    budget = models.DecimalField(max_digits=10,decimal_places=0)
    goal = models.TextField()
    state =models.ForeignKey(State,on_delete=models.CASCADE)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    img=models.FileField(upload_to="pic/%y/",default="")
    convocatory = models.ForeignKey(Convocatory,on_delete=models.SET_NULL, blank=True, null = True)
    def __str__(self):
        return self.project_name
    class Meta :
        ordering=('-project_id',)

class Binnacle(models.Model):
    #Primary key
    binnacle_id = models.CharField(max_length=5)
    #Foreing key
    project_id = models.ForeignKey(Project,on_delete = models.CASCADE)

class Log(models.Model):
    #Primary key
    log_id = models.CharField(max_length=10)

    log_name = models.CharField(max_length=30)
    date_time = models.DateTimeField()
    observations = models.TextField()
    results = models.TextField()
 
    #Foreing Key
    binnacle_id = models.ForeignKey(Binnacle,models.CASCADE)

class Donation(models.Model):
    donation_id= models.AutoField(primary_key=True)
    amount = models.DecimalField(max_digits=10,decimal_places=0)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)

class Suggestion(models.Model):
    suggestion_id = models.AutoField(primary_key=True)
    suggestion_name = models.CharField(max_length=50)
    suggestion_description = models.TextField()
    suggestion_work_plan = models.TextField()
    suggestion_budget = models.DecimalField(max_digits=10,decimal_places=0)

class Comments(models.Model):
    comment_id = models.AutoField(primary_key=True)
    author= models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(default=timezone.now())
    project = models.ForeignKey(Project,on_delete=models.CASCADE)

class Beneficiary(models.Model):
    beneficiary_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(Client,on_delete=models.CASCADE)
    email = models.CharField(max_length=40)
    phone_number = models.CharField(max_length=20)
    representative_name = models.CharField(max_length=30)
    phone_number_representative = models.CharField(max_length=20)
    is_approved = models.BooleanField(null=True,blank=True)
    project = models.ForeignKey(Project,on_delete=models.CASCADE)

core/forms.py
from django import forms
from .models import Category,State,Project,Convocatory,Donation, Suggestion, Comments,Beneficiary
from django.core import validators



class Edit_category_form(forms.ModelForm):
    class Meta :
        model = Category
        fields = [
            'category_name',
            'icon_src',
            'description',
        ]
        widgets = {
            'category_name':forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Nombre:'}),
            'icon_src':forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Ruta icono:'}),
            'description':forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Descripción:'}),
        }


class State_form(forms.ModelForm):
    class Meta :
        model = State
        fields = [
            'state_name',
            'description',
        ]
        widgets = {
            'state_name':forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Nombre:'}),
            'description':forms.TextInput(attrs={'class': 'form-control mb-3', 'placeholder': 'Descripción:'}),
        }


class Project_form(forms.ModelForm):
    class Meta :
        model = Project
        fields = [
            'project_name',
            'project_description',
            'result',
            'scope',
            'work_plan',
            'budget',
            'goal',
            'img',
            'state',
            'category',
            'convocatory',
        ]
        widgets = {

            'project_name':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Nombre:'}),
            'project_description':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Descripción:'}),
            'result':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Resultado:'}),
            'scope':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Objetivo:'}),
            'work_plan':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Plan de trabajo:'}),
            'budget':forms.NumberInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Presupuesto:'}),
            'goal':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Meta:'}),
            'img':forms.FileInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Imagen:'}),
            'state': forms.Select(attrs={'class': ''}),
            'category': forms.Select(attrs={'class': ''}),
            'convocatory': forms.Select(attrs={'class': 'form-control mb-1', 'placeholder': 'Convocatoria:'}),
            
        }





class Convocatory_form(forms.ModelForm):
    class Meta :
        model = Convocatory
        fields = [
            'convocatory_name',
            'start_date',
            'closing_date',
        ]
        widgets = {
            'convocatory_name':forms.TextInput(attrs={'size': 30,'class': 'form-control', 'placeholder': 'Nombre:'}),
            'start_date': forms.DateInput(attrs={'type': 'date','class': 'form-control', 'placeholder': 'Fecha inicio:'}),
            'closing_date': forms.DateInput(attrs={'type': 'date','class': 'form-control ', 'placeholder': 'Fecha Fin:'}),
        }

class Suggestion_form(forms.ModelForm):
     class Meta :
        model = Suggestion
        fields = [
            'suggestion_name',
            'suggestion_description',
            'suggestion_work_plan',
            'suggestion_budget',
        ]
        widgets = {
            'suggestion_name':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Nombre'}),
            'suggestion_description':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Descripción'}),
            'suggestion_work_plan':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Plan de trabajo'}),
            'suggestion_budget':forms.NumberInput(attrs={'class': 'input', 'placeholder': ''}),
        }

class Comment_form(forms.ModelForm):
     class Meta :
        model = Comments
        fields = [
            'text',
        ]
        widgets = {
            'text':forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Comenta'}),
        }

class Beneficiary_form(forms.ModelForm):
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'input', 'placeholder': ''}),required=True),

    class Meta :
        model = Beneficiary
        fields = [
            'email',
        ]
        widgets = {
            'email':forms.TextInput(attrs={'class': 'input', 'placeholder': ''}),
        }

core/templates/employee_views/beneficiaries_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}

<div class="container">
    <div class="row">
        <h1 class="font-weight-bold mb-0">Bienvenido</h1>
        <p class="lead text-muted">Revisa la última información de los Beneficiarios</p>

        <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filtro
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'core:ebeneficiaries' %}
                ">Todos</a>
                <a class="dropdown-item" href="{% url 'core:ebeneficiaries' %}?lang=True
                ">Aprobados</a>
                <a class="dropdown-item" href="{% url 'core:ebeneficiaries' %}?lang=False
                ">Desaprobados</a>
            </div>
        </div>


    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="list-container overflow-auto" style="max-height: 360px;">
                <ul class="list-group" style="margin-top:10px;">
                    {% for e in beneficiaries %}
                    <li class="list-group-item">
                        <div class="row">

                            <div class="col-md-8">
                                <h5>Empresa: {{ e.user.name }}</h5>
                                <p>Representante:{{ e.user.representative_name }}</p>
                                <p>Tel Empresa:{{ e.phone_number }}</p>
                                <p>Email: {{ e.email }}</p>
                            </div>
                            <div class="row-md-2">
                                <div class="btn-group-vertical">
                                    <td><a href="{{ e.beneficiary_id }}?lang=True" class="btn btn-info mb-4"
                                            style="background-color: #087F8C;color: white;border-radius: 8px;">Aprobar</a>
                                    </td>

                                </div>
                                <div class="btn-group-vertical">
                                    <td><a href="{{ e.beneficiary_id }}?lang=False" class="btn btn-info mb-4"
                                            style="background-color: #087F8C;color: white;border-radius: 8px;">Desaprobar</a>
                                    </td>

                                </div>

                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>




<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>



{% endblock %}

core/templates/employee_views/change_password_employee_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <h2>Cambiar contraseña</h2>
        <div id="alert-container">
        </div>
        <form method="post">

            </div>
            <div class="row">
                <div class="col-md-6 mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">Contraseña:</label>
                        {{ form.password }}

                    </div>
                    <div class="form-group">
                        <label for="">Confirmar nueva contraseña:</label>
                        {{ form.new_password_confirmation }}
                    </div>

                </div>

                <div class="col-md-6 mb-4 align-self-start">
                    <div class="form-group">
                        <label for="">Nueva contraseña:</label>
                        {{ form.new_password }}


                    </div>

                </div>
            </div>

            <center>
                <div class="row">
                    <div class="col d-flex justify-content-center">

                        <a href="{% url 'core:edit_employee_ehome' username=user %}" class="btn btn-success" style="background-color:white; color:#087F8C;border-color: #087F8C;height: 40px;width: 200px;">Cancelar</a>

                    
                        <button type="submit" class="btn btn-success" style="background-color:#087F8C;color:white;height: 40px;width: 200px;margin-left: 10px;">Guardar</button>
                    </div>
                </div>
            </center>
            
            
        </form>
    </div>
</div>
{% endblock %}

core/templates/employee_views/convocatories_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}
<h4>Convocatorias </h4>
<a href="save">
    <button class="btn btn-succes" style="background-color:#087F8C;color:white">Añadir</button>
</a>


<div class="row">

    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4"></div>
    <div class="table-responsive etable">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Fecha inicio</th>
                    <th>Fecha fin</th>
                    <th colspan="">Opciones</th>
                </tr>
            </thead>
            <tbody>
                {% for c in convocatories %}
                <tr>
                    <td>{{ c.convocatory_name }}</td>
                    <td>{{ c.start_date }}</td>
                    <td>{{ c.closing_date }}</td>
                    <td><a href="edit/{{c.convocatory_id}}" class="btn btn-info">Editar</a></td>
                    <td><a href="delete/{{c.convocatory_id}}" class="btn btn-danger">Borrar</a></td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{% endblock %}

core/templates/employee_views/crud_convocatory_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}
<section >
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">

            <div id="alert-container">

            </div>
            <h2>{{title}}</h2>
            <form method="post">
                
                <div class="row">
                    <div class="col-md-6 mb-4">
                        {% csrf_token %}


                        {% if title == 'Editar Convocatoria' %}

                            <div class="form-group">                        
                                <label>Id:</label>
                                <input type="" class="form-control mb-3" id="id_convocatory_id" value="{{convocatory.convocatory_id }}"readonly>
                        
                            </div>


                        {% endif %}
                        <div class="form-group">
                            <label for="">Nombre:</label>
                            {{ form.convocatory_name }}
                        </div>
                    </div>
                    <div class="col-md-6 mb-4 align-self-start">
                        <div class="form-group">
                            <label for="">Fecha inicio:</label>
                            {{ form.start_date }}
                        </div>
                        <div class="form-group">
                            <label for="">Fecha fin:</label>
                            {{ form.closing_date }}
                        </div>
                    </div>
                </div>

                <center>
                    <button type="submit" class="btn btn-succes" style="background-color:#087F8C;color:white">Guardar</button>
                </center>
            </form>
        </div>

    </div>
</section>

{% endblock %}

core/templates/employee_views/crud_employee_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}
<div class="container py-2 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <h2>{{title}}</h2>
        <div id="alert-container">

        </div>

        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6 mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.nit.id_for_label }}">Cedula:</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.nit.id_for_label }}">Contraseña:</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group">
                        <label for="{{ form.nit.id_for_label }}">Confirmar contraseña:</label>
                        {{ form.password_confirmation }}
                    </div>


                    <div class="form-group">
                        <label for="">Foto de empleado:</label>
                        {{ form.img }}
                    </div>
                </div>
                
                <div class="col-md-6 mb-4 align-self-start">

                    <div class="form-group">
                        <label for="">Nombre:</label>
                        {{ form.first_name }}
                    </div>

                    <div class="form-group">
                        <label for="">Apellido:</label>
                        {{ form.last_name }}
                    </div>

                    <div class="form-group">
                        <label for="">Fecha de nacimiento:</label>
                        {{ form.birth_date }}
                    </div>


                </div>
            </div>
            <center>
                <button type="submit" class="btn btn-success"
                    style="background-color:#087F8C;color:white">Guardar</button>
                <a href="{% url 'core:etools' %}" class="btn btn-success" style="background-color:white;        color:#087F8C;border-color: #087F8C;">Cancelar</a>
            </center>
        </form>
    </div>

</div>


{% endblock %}

core/templates/employee_views/crud_project_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}
<section >
    <div class="container  h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">

            <div id="alert-container">

            </div>
            <h2>{{title}}</h2>
            <form method="post" enctype="multipart/form-data">
                
                <div class="row">
                    <div class="col-md-6 mb-4">
                        {% csrf_token %}


                        {% if title == 'Editar Proyecto' %}

                            <div class="form-group">                        
                                <label>Id de estado:</label>
                                <input type="" class="form-control mb-3" id="id_state_id" value="{{ project.project_id }}"readonly>
                            </div>

                        {% endif %}
                        <div class="form-group">
                            <label for="">Nombre:</label>
                            {{ form.project_name }}
                        </div>
                        <div class="form-group">
                            <label for="">Descripción:</label>
                            {{ form.project_description }}
                        </div>
                        <div class="form-group">
                            <label for="">Resultado:</label>
                            {{ form.result }}
                        </div>
                        <div class="form-group">
                            <label for="">Objetivo:</label>
                            {{ form.scope }}
                        </div>
                        <div class="form-group">
                            <label for="">Presupuesto:</label>
                            {{ form.budget}}
                        </div>
                    </div>
                    <div class="col-md-6 mb-4 align-self-start">
                        <div class="form-group">
                            <label for="">Plan de trabajo:</label>
                            {{ form.work_plan }}
                        </div>
                        <div class="form-group">
                            <label for="">Convocatoria:</label>
                            
                            {{ form.convocatory }}
                        </div>
                        <div class="form-group">
                            <label for="">Meta:</label>
                            {{ form.goal}}
                        </div>
                        <div class="form-group">
                            <label for="">Imagen:</label>
                            {{ form.img}}
                        </div>
                        <div class="form-group">
                            {{form.state}}
                            {{form.category}}
                        </div>
                        <div class="form-group">

                           

                        </div>
                    </div>
                </div>

                <center>
                    <button type="submit" class="btn btn-succes" style="background-color:#087F8C;color:white">Guardar</button>
                </center>
            </form>
        </div>

    </div>
</section>

{% endblock %}

core/templates/employee_views/crud_states_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}
<section >
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">

            <div id="alert-container">

            </div>
            <h2>{{title}}</h2>
            <form method="post">
                
                <div class="row">
                    <div class="col-md-6 mb-4">
                        {% csrf_token %}


                        {% if title == 'Editar Estado' %}

                            <div class="form-group">                        
                                <label>Id de estado:</label>
                                <input type="" class="form-control mb-3" id="id_state_id" value="{{ state.state_id }}"readonly>
                        
                            </div>


                        {% endif %}
                        <div class="form-group">
                            <label for="">Nombre:</label>
                            {{ form.state_name }}
                        </div>
                    </div>
                    <div class="col-md-6 mb-4 align-self-start">
                        <div class="form-group">
                            <label for="">Descripción:</label>
                            {{ form.description }}
                        </div>
                    </div>
                </div>

                <center>
                    <button type="submit" class="btn btn-succes" style="background-color:#087F8C;color:white">Guardar</button>
                </center>
            </form>
        </div>

    </div>
</section>

{% endblock %}

core/templates/employee_views/edit_employee_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}

<div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <h2>{{title}}</h2>
        <div id="alert-container">
        </div>
        <form method="post" enctype="multipart/form-data">
            <div class="text-align">
                <div class="text-center">
                    <img id="preview-image" src="{{ img.url }}" style="width:100px; height:100px; border-radius: 10px;">

                </div>
                <div class="form-group">
                    <label for="" style="text-align: left;">Cambiar foto:</label>

                    {{form.img}}
                </div>
            </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.nit.id_for_label }}">Cedula:</label>
                        {{ form.username }}

                    </div>
                    <div class="form-group">
                        <label for="">Nombre:</label>
                        {{ form.first_name }}
                    </div>
                </div>

                <div class="col-md-6 mb-4 align-self-start">
                    <div class="form-group">
                        <label for="">Apellido:</label>
                        {{ form.last_name }}
                    </div>
                    <div class="form-group">
                        <label for="">Fecha de nacimiento:</label>
                        {{ form.birth_date }}
                    </div>
                </div>
            </div>
            <center>
                <div class="row">
                    <div class="col d-flex justify-content-center">

                        <a href="{% url 'core:etools' %}" class="btn btn-success" style="background-color:white; color:#087F8C;border-color: #087F8C;height: 40px;width: 200px;">Cancelar</a>

                    
                        <button type="submit" class="btn btn-success" style="background-color:#087F8C;color:white;height: 40px;width: 200px;margin-left: 10px;">Guardar</button>
                    </div>
                </div>
            </center>
            
            
        </form>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $("#id_img").change(function() {
    var input = $(this)[0];
    
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      
      reader.onload = function(e) {
        // Actualizar la imagen de vista previa
        $("#preview-image").attr("src", e.target.result);
      }
      
      reader.readAsDataURL(input.files[0]);
    }
  });
});
</script>


{% endblock %}