Auth/urls.py
from django.urls import path
from .views import User_login_view,Client_register_view
from Auth import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'auth'

urlpatterns = [
    path('register/',Client_register_view.as_view(),name='register'),
    path('login/',User_login_view.as_view(),name='login'),
    path('logout/',views.logout_request,name='logout'),
]

core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from core import views
from core.views import detailed_info
from core.views import binnacle
from core.views import Project_view
from core.views import Gallery
from core.views import Donation_methods
from core.views import Successful_donation
from core.views import Convocatory_inscription
from core.views import Suggestion_view
app_name = 'core'
base_url_employee = 'ehome/'

urlpatterns = [
    path('donation/<project_id>', views.Stripe_donation.as_view(), name='donation'),
    path('', views.Home_view.as_view(), name='home'),
    path('home/', views.Home_view.as_view(), name='home'),
    path('categories/', views.Categories_view.as_view(), name='categories'),
    path('detailedinfo/', detailed_info.as_view(), name='detailedinfo'),
    path('binnacle/', binnacle.as_view(), name='binnacle'),
    path(base_url_employee, views.Home_view_employee.as_view(), name='employee_home'),
    path('gallery/', Gallery.as_view(), name ='gallery'),
    path('project/', Project_view.as_view(), name ='project'),
    path('donation_methods/', Donation_methods.as_view(), name='donation_methods'),
    path('ehome/categories/',views.Employee_categories.as_view(),name='ecategories'),
    path('ehome/projects/',views.Employee_projects.as_view(),name='eprojects'),
    path('ehome/beneficiaries/',views.Employee_beneficiaries.as_view(),name='ebeneficiaries'),
    path('ehome/beneficiaries/<beneficiary_id>',views.Edit_beneficiaries.as_view(),name='e_edit_beneficiaries'),
    path(base_url_employee+'categories/',views.Employee_categories.as_view(),name='ecategories'),
    path(base_url_employee+'convocatories/',views.Employee_convocatories.as_view(),name='econvocatories'),
    path(base_url_employee+'clients/',views.Employee_clients.as_view(),name='eclients'),
    path(base_url_employee+'tools/',views.Employee_tools.as_view(),name='etools'),
    path(base_url_employee+'categories/edit/<category_id>',views.Edit_category.as_view(),name='edit_category_ehome'),
    path(base_url_employee+'categories/delete/<category_id>',views.Delete_category.delete_category,name='delete_category_ehome'),
    path(base_url_employee+'categories/save',views.Save_Category.as_view(),name='save_category_ehome'),
    path(base_url_employee+'states/',views.Employee_states.as_view(),name='estates'),
    path(base_url_employee+'states/edit/<state_id>',views.Edit_state.as_view(),name='edit_state_ehome'),
    path(base_url_employee+'states/delete/<state_id>',views.Delete_state.delete_state,name='delete_state_ehome'),
    path(base_url_employee+'states/save',views.Save_state.as_view(),name='save_state_ehome'),
    path(base_url_employee+'tools/save',views.Save_employee.as_view(),name='save_employee_ehome'),
    path(base_url_employee+'projects/edit/<project_id>',views.Edit_project.as_view(),name='edit_project_ehome'),
    path(base_url_employee+'projects/save',views.Save_project.as_view(),name='save_project_ehome'),
    path(base_url_employee+'projects/delete/<project_id>',views.Delete_project.delete_project,name='delete_project_ehome'),
    path('convocatory',Convocatory_inscription.as_view(),name='convocatory'),
    path(base_url_employee+'convocatories/save',views.Save_convocatories.as_view(),name='save_convocatory_ehome'),
    path(base_url_employee+'convocatories/edit/<convocatory_id>',views.Edit_convocatory.as_view(),name='edit_convocatory_ehome'),
    path(base_url_employee+'convocatories/delete/<convocatory_id>',views.Delete_convocatory.delete_convocatory,name='delete_convocatory_ehome'),
    path(base_url_employee+'tools/edit/<username>',views.Edit_employee.as_view(),name='edit_employee_ehome'),
    path(base_url_employee+'tools/delete/<username>',views.Delete_employe.delete_employee,name='delete_employee_ehome'),
    path('suggestions/',Suggestion_view.as_view(),name='suggestions'),
]

urlpatterns += staticfiles_urlpatterns()

knowledge_projects/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Auth.urls')),
    path('',include('core.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views import View
from core.models import Category,Project,State,Convocatory,Donation, Suggestion, Comments, Beneficiary
from Auth.forms import Employee_register_form,Employee_edit_form,Employee_change_password
from .forms import Edit_category_form,State_form,Project_form,Convocatory_form,Suggestion_form, Comment_form,Beneficiary_form
from Auth.models import Client,Employee,User
from django.urls import reverse
from django.contrib.auth.hashers import check_password,make_password
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator





import stripe


SECRET_KEY = "sk_test_51NFiTZLtn7velaE9MPVYsbbL1R9yZ57rWnyR8RLW9mE8SvoFy9Unvf0WQq81vugXUj2ZPH8ccfBIzYJ3GPKPrG6d00nalYbtJf"

stripe.api_key=SECRET_KEY


# Create your views here.


class Project_view(View):
    def get(self,request):
        obj = Project.objects.all()
        obj1 = Project.objects.all()
        card_id= self.request.GET.get("lang")
        p = Project.objects.get(project_id = card_id)
        convocatory = None
        donations = Donation.objects.all()

        if (donations):
            donations = donations.get(project = card_id)
        if (p.convocatory):
            convocatory = p.convocatory

        if card_id:
            obj= obj.filter(project_id=card_id)[0]
            obj1=obj1.filter(category = p.category.category_id)
            obj1=obj1.exclude(project_id= card_id)
        return HttpResponse(render(request,'project.html',{'project':obj, 'related':obj1, 'don':donations, 'conv': convocatory})) 
class Donation_methods(View):
    def get(self,request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        obj = obj.filter(project_id=card_id)
        context={
            'card': obj
        }
        return HttpResponse(render(request,'donation_methods.html',context))
    
    def post(self, request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        obj = obj.get(project_id=card_id)
        form = Donation_form(request.POST)
        if form.is_valid():
            donation = Donation()
            donation.payment_method = form.cleaned_data['payment_method']
            donation.amount = form.cleaned_data['amount']
            donation.user = request.user
            donation.project = obj
            donation.save()
            return redirect('core:successful_donation')  
        context={
            'form': Donation_form,
            'card': obj
        }
        return render(request, 'donation_methods.html', context)
    
@method_decorator(login_required, name='dispatch')
class Stripe_donation(View):
    def get(self, request,project_id):

        project = Project.objects.get(project_id=project_id)
        amount = project.budget

        context={
            'project':project,
            'amount': amount,
        }

        return HttpResponse(render(request,'donation_views/stripe_donation_view.html',context))

    def post(self, request,project_id):
        token = request.POST.get('stripeToken')
        email = request.POST.get('email')

  

        project = Project.objects.get(project_id=project_id)  
        amount = project.budget

        try:

            charge = stripe.Charge.create(
                amount=amount*100,  # Monto en centavos de la moneda especificada
                currency='usd',  # Moneda
                source=token,
                description='Ejemplo de pago con Stripe',
            )



            context={
                'project':project,
            }

            print('aqui')

            donation = Donation()
            donation.amount = project.budget
            donation.user = request.user
            donation.project = project
            donation.save()


            return HttpResponse(render(request,'successful_donation.html',context))

        
        except stripe.error.CardError as e:
            error = e.error.message
            context={
                'project':project,
                'amount': amount,
                'error':error,
            }

            return HttpResponse(render(request,'donation_views/stripe_donation_view.html',context))



class Home_view(View):   
    def get(self, request):
        username = None
        if request.user.is_authenticated:
            username = request.user.username
            context = {"username" : 'Hola, ' + username,}
            return HttpResponse(render(request,'home_view.html',context))
        
        return HttpResponse(render(request,'home_view.html'))

class Categories_view(View):   
    def get(self, request):
        data = Category.objects.all()
        context={
        'data': data
        }
        return HttpResponse(render(request,'categories_view.html',context))


@method_decorator(login_required, name='dispatch')
class detailed_info(View):
    def get(self,request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        if card_id:
            obj= obj.filter(project_id=card_id)[0]
        comment = Comments.objects.filter(project = card_id)
        donations = Donation.objects.filter(project = card_id)

        context={
            'form': Comment_form,
            'project':obj,
            'com':comment,
            'don':donations
        }
        return HttpResponse(render(request,'detailedinfo.html',context))
    
    def post(self, request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        if card_id:
            obj= obj.filter(project_id=card_id)[0]
        comment = Comments.objects.filter(project = card_id)
        donations = Donation.objects.filter(project = card_id)

        context={
            'form': Comment_form,
            'project':obj,
            'com':comment,
            'don':donations
        }
        
        form = Comment_form(request.POST)
        if form.is_valid():
            comment = Comments()
            comment.author = request.user
            comment.text = form.cleaned_data['text']
            comment.project = obj
            comment.save()

        return render(request, 'detailedinfo.html', context)

class binnacle(View):
    def get(self,request):
      return render(request,'binnacle.html')

@method_decorator(login_required, name='dispatch')
class Home_view_employee(View):   
    def get(self, request):
        n_projects =Project.objects.count()
        n_donations =Donation.objects.count()
        n_convocatories =Convocatory.objects.count()
        n_clients = Client.objects.count()

        context={
            'active': 'dashboard',
            'n_projects':n_projects,
            'n_donations':n_donations,
            'n_convocatories':n_convocatories,
            'n_clients':n_clients,


        }
        return HttpResponse(render(request,'employee_views/employee_home_view.html',context))
    
    
class Employee_clients(View):   
    def get(self, request):
        context={
            'active': 'clients',
        }
        return HttpResponse(render(request,'clients_ehome.html',context))
    
class Employee_tools(View):   
    def get(self, request):
        employees = Employee.objects.all()

        context={
            'active': 'tools',
            'user':request.user,
            'employees':employees,
        }
        return HttpResponse(render(request,'tools_ehome.html',context))
    
class Gallery(View):
     def get(self,request):
        obj = Project.objects.all()
        category_id= self.request.GET.get("lang")
        if category_id:
            obj= obj.filter(category = category_id)
        return HttpResponse(render(request,'gallery.html',{'card':obj}))
     


class Employee_tools(View):   
    def get(self, request):
        employees = Employee.objects.all()
        context={
            'active': 'tools',
            'user':request.user,
            'employees':employees,
        }
        return HttpResponse(render(request,'employee_views/tools_ehome.html',context))

#Employee CRUD
@method_decorator(login_required, name='dispatch')
class Save_employee(View):
    def get(self,request):
        context={
            'title' : 'Guardar empleado',
            'active': 'tools',
            'form': Employee_register_form(),
        }
        return HttpResponse(render(request,'employee_views/crud_employee_ehome.html',context))
    
    def post(self, request):
        form = Employee_register_form(request.POST,request.FILES)
        if form.is_valid():

            user = User()
            user.username = form.cleaned_data['username']
            user.password = form.cleaned_data['password']
            user.is_client = False  
            user.is_employee = True  
            user.save()
            
            employee = Employee.objects.create(
                user=user,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                birth_date=form.cleaned_data['birth_date'],
                img=form.cleaned_data['img']    
            )

            order = form.save(commit=False) 
            order.user = user 
            order.save() 

            return redirect('core:etools')
        
        context = {
            'title': 'Guardar Empleados',
            'active': 'tools',
            'form': form,
        }
        return render(request, 'employee_views/crud_employee_ehome.html', context)
    
class Delete_employe(View):
    def delete_employee(request,username):
        user = User.objects.get(username=username)
        user.delete()
        return redirect('core:etools')
    
class Change_employee_password(View):
    def get(self,request,username):


        context={
            'user':username,
            'form':Employee_change_password(),

core/templates/layouts/core/base_employee_view.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/style_sidebar.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/etable.css' %}" />

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

  <title>Employee Home</title>
</head>

<body>


  <div class="main-container d-flex d-flex" id="side_nav_div" >
    <div class="sidebar sidebar-container" id="side_nav">
      <div class="header-box px-2 pt-3 pb-4 d-flex justify-content-between">

        <h1 class="fs-4"><img src="/media/pic/admin_view/STR_Certification-1024x254.png" id="logo_image" alt="logo">
        </h1>
        <button class="btn d-md-none d-block close-btn "><i class="bi bi-list"></i></i></button>
      </div>
      <ul class="list-unstyled px-2">
        <li class="{% if active == 'dashboard' %}active{% endif %}"><a href="{% url 'core:employee_home' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-list"></i>Tablero</a></li>
        <li class="{% if active == 'categories' %}active{% endif %}"><a href="{% url 'core:ecategories' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-tags-fill"></i>Categorías</a></li>
        <li class="{% if active == 'states' %}active{% endif %}"><a href="{% url 'core:estates' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-activity"></i>Estados</a></li>

        <li class="{% if active == 'projects' %}active{% endif %}"><a href="{% url 'core:eprojects' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-box-seam-fill"></i>Proyectos</a></li>

        <li class="{% if active == 'convocatories' %}active{% endif %}"><a href="{% url 'core:econvocatories' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-calendar-check-fill"></i>Convocatorias</a>
        </li>
        <li class="{% if active == 'clients' %}active{% endif %}"><a href="{% url 'core:eclients' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-people-fill"></i>Clientes</a></li>
            <li class="{% if active == 'beneficiaries' %}active{% endif %}"><a href="{% url 'core:ebeneficiaries' %}"
              class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-award-fill"></i>Beneficiarios</a></li>

      </ul>
      <hr class="h-color mx-2">
      <ul class="list-unstyled px-2">
        <li class="{% if active == 'tools' %}active{% endif %}"><a href="{% url 'core:etools' %}"
            class="text-decoration-none px-3 py-2 d-block"><i class="bi bi-gear-fill"></i>Administrador</a></li>
      </ul>



    </div>
    <div class="content">

      <nav class="navbar navbar-expand-lg bg-body-tertiary mr-auto">
        <div class="container-fluid">
          <div class="d-flex justify-content-between d-md-none d-block">
            <button class="btn px-1 py-0 open-btn"><i class="bi bi-list"></i></button>
          </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

              <li class="nav-item active">
                <div class="flex-shrink-0">

                  {% if user.is_admin %}
                    
                  {% else %}

                    <img src="{{ user.Employee.img.url }}"
                    class="img-fluid rounded-circle border border-1"
                    style="width: 35px;height: 35px;">

                  {% endif %}

                </div>
              </li>

              <li class="nav-item dropdown">
                
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                  aria-expanded="false">

                  {% if user.is_admin %}
                    {{ user.first_name }} {{ user.last_name}}
                  {% else %}
                  {{ user.Employee.first_name }} {{ user.Employee.last_name}}

                  {% endif %}
                </a> 
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><a class="dropdown-item" href="#">Mi pérfil</a></li>
                  <li><a class="dropdown-item" href="#">Ayuda</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Cerrar sesión</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="dashboard-content px-3" id="content_body">
        {% block content%}

        {% endblock %}
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script>

    $(".sidebar ul li").on('click', function () {
      $(".sidebar ul li.active").removeClass('active');
      $(this).addClass('active');
    });

    $('.open-btn').on('click', function () {
      $('.sidebar').addClass('active')
    });

    $('.close-btn').on('click', function () {
      $('.sidebar').removeClass('active')
    });


  </script>



</body>

</html>