Auth/urls.py
from django.urls import path
from .views import User_login_view,Client_register_view
from Auth import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'auth'

urlpatterns = [
    path('register/',Client_register_view.as_view(),name='register'),
    path('login/',User_login_view.as_view(),name='login'),
    path('logout/',views.logout_request,name='logout'),
]

core/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from core import views
from core.views import detailed_info
from core.views import binnacle
from core.views import Project_view
from core.views import Gallery
from core.views import Donation_methods
from core.views import Successful_donation
from core.views import Convocatory_inscription
from core.views import Suggestion_view
app_name = 'core'
base_url_employee = 'ehome/'

urlpatterns = [
    path('donation/<project_id>', views.Stripe_donation.as_view(), name='donation'),
    path('', views.Home_view.as_view(), name='home'),
    path('home/', views.Home_view.as_view(), name='home'),
    path('categories/', views.Categories_view.as_view(), name='categories'),
    path('detailedinfo/', detailed_info.as_view(), name='detailedinfo'),
    path('binnacle/', binnacle.as_view(), name='binnacle'),
    path(base_url_employee, views.Home_view_employee.as_view(), name='employee_home'),
    path('gallery/', Gallery.as_view(), name ='gallery'),
    path('project/', Project_view.as_view(), name ='project'),
    path('donation_methods/', Donation_methods.as_view(), name='donation_methods'),
    path('ehome/categories/',views.Employee_categories.as_view(),name='ecategories'),
    path('ehome/projects/',views.Employee_projects.as_view(),name='eprojects'),
    path('ehome/beneficiaries/',views.Employee_beneficiaries.as_view(),name='ebeneficiaries'),
    path('ehome/beneficiaries/<beneficiary_id>',views.Edit_beneficiaries.as_view(),name='e_edit_beneficiaries'),
    path(base_url_employee+'categories/',views.Employee_categories.as_view(),name='ecategories'),
    path(base_url_employee+'convocatories/',views.Employee_convocatories.as_view(),name='econvocatories'),
    path(base_url_employee+'clients/',views.Employee_clients.as_view(),name='eclients'),
    path(base_url_employee+'tools/',views.Employee_tools.as_view(),name='etools'),
    path(base_url_employee+'categories/edit/<category_id>',views.Edit_category.as_view(),name='edit_category_ehome'),
    path(base_url_employee+'categories/delete/<category_id>',views.Delete_category.delete_category,name='delete_category_ehome'),
    path(base_url_employee+'categories/save',views.Save_Category.as_view(),name='save_category_ehome'),
    path(base_url_employee+'states/',views.Employee_states.as_view(),name='estates'),
    path(base_url_employee+'states/edit/<state_id>',views.Edit_state.as_view(),name='edit_state_ehome'),
    path(base_url_employee+'states/delete/<state_id>',views.Delete_state.delete_state,name='delete_state_ehome'),
    path(base_url_employee+'states/save',views.Save_state.as_view(),name='save_state_ehome'),
    path(base_url_employee+'tools/save',views.Save_employee.as_view(),name='save_employee_ehome'),
    path(base_url_employee+'projects/edit/<project_id>',views.Edit_project.as_view(),name='edit_project_ehome'),
    path(base_url_employee+'projects/save',views.Save_project.as_view(),name='save_project_ehome'),
    path(base_url_employee+'projects/delete/<project_id>',views.Delete_project.delete_project,name='delete_project_ehome'),
    path('convocatory',Convocatory_inscription.as_view(),name='convocatory'),
    path(base_url_employee+'convocatories/save',views.Save_convocatories.as_view(),name='save_convocatory_ehome'),
    path(base_url_employee+'convocatories/edit/<convocatory_id>',views.Edit_convocatory.as_view(),name='edit_convocatory_ehome'),
    path(base_url_employee+'convocatories/delete/<convocatory_id>',views.Delete_convocatory.delete_convocatory,name='delete_convocatory_ehome'),
    path(base_url_employee+'tools/edit/<username>',views.Edit_employee.as_view(),name='edit_employee_ehome'),
    path(base_url_employee+'tools/delete/<username>',views.Delete_employe.delete_employee,name='delete_employee_ehome'),
    path('suggestions/',Suggestion_view.as_view(),name='suggestions'),
]

urlpatterns += staticfiles_urlpatterns()

knowledge_projects/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Auth.urls')),
    path('',include('core.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views import View
from core.models import Category,Project,State,Convocatory,Donation, Suggestion, Comments, Beneficiary
from Auth.forms import Employee_register_form,Employee_edit_form,Employee_change_password
from .forms import Edit_category_form,State_form,Project_form,Convocatory_form,Suggestion_form, Comment_form,Beneficiary_form
from Auth.models import Client,Employee,User
from django.urls import reverse
from django.contrib.auth.hashers import check_password,make_password
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator





import stripe


SECRET_KEY = "sk_test_51NFiTZLtn7velaE9MPVYsbbL1R9yZ57rWnyR8RLW9mE8SvoFy9Unvf0WQq81vugXUj2ZPH8ccfBIzYJ3GPKPrG6d00nalYbtJf"

stripe.api_key=SECRET_KEY


# Create your views here.


class Project_view(View):
    def get(self,request):
        obj = Project.objects.all()
        obj1 = Project.objects.all()
        card_id= self.request.GET.get("lang")
        p = Project.objects.get(project_id = card_id)
        convocatory = None
        donations = Donation.objects.all()

        if (donations):
            donations = donations.get(project = card_id)
        if (p.convocatory):
            convocatory = p.convocatory

        if card_id:
            obj= obj.filter(project_id=card_id)[0]
            obj1=obj1.filter(category = p.category.category_id)
            obj1=obj1.exclude(project_id= card_id)
        return HttpResponse(render(request,'project.html',{'project':obj, 'related':obj1, 'don':donations, 'conv': convocatory})) 
class Donation_methods(View):
    def get(self,request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        obj = obj.filter(project_id=card_id)
        context={
            'card': obj
        }
        return HttpResponse(render(request,'donation_methods.html',context))
    
    def post(self, request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        obj = obj.get(project_id=card_id)
        form = Donation_form(request.POST)
        if form.is_valid():
            donation = Donation()
            donation.payment_method = form.cleaned_data['payment_method']
            donation.amount = form.cleaned_data['amount']
            donation.user = request.user
            donation.project = obj
            donation.save()
            return redirect('core:successful_donation')  
        context={
            'form': Donation_form,
            'card': obj
        }
        return render(request, 'donation_methods.html', context)
    
@method_decorator(login_required, name='dispatch')
class Stripe_donation(View):
    def get(self, request,project_id):

        project = Project.objects.get(project_id=project_id)
        amount = project.budget

        context={
            'project':project,
            'amount': amount,
        }

        return HttpResponse(render(request,'donation_views/stripe_donation_view.html',context))

    def post(self, request,project_id):
        token = request.POST.get('stripeToken')
        email = request.POST.get('email')

  

        project = Project.objects.get(project_id=project_id)  
        amount = project.budget

        try:

            charge = stripe.Charge.create(
                amount=amount*100,  # Monto en centavos de la moneda especificada
                currency='usd',  # Moneda
                source=token,
                description='Ejemplo de pago con Stripe',
            )



            context={
                'project':project,
            }

            print('aqui')

            donation = Donation()
            donation.amount = project.budget
            donation.user = request.user
            donation.project = project
            donation.save()


            return HttpResponse(render(request,'successful_donation.html',context))

        
        except stripe.error.CardError as e:
            error = e.error.message
            context={
                'project':project,
                'amount': amount,
                'error':error,
            }

            return HttpResponse(render(request,'donation_views/stripe_donation_view.html',context))



class Home_view(View):   
    def get(self, request):
        username = None
        if request.user.is_authenticated:
            username = request.user.username
            context = {"username" : 'Hola, ' + username,}
            return HttpResponse(render(request,'home_view.html',context))
        
        return HttpResponse(render(request,'home_view.html'))

class Categories_view(View):   
    def get(self, request):
        data = Category.objects.all()
        context={
        'data': data
        }
        return HttpResponse(render(request,'categories_view.html',context))


@method_decorator(login_required, name='dispatch')
class detailed_info(View):
    def get(self,request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        if card_id:
            obj= obj.filter(project_id=card_id)[0]
        comment = Comments.objects.filter(project = card_id)
        donations = Donation.objects.filter(project = card_id)

        context={
            'form': Comment_form,
            'project':obj,
            'com':comment,
            'don':donations
        }
        return HttpResponse(render(request,'detailedinfo.html',context))
    
    def post(self, request):
        obj = Project.objects.all()
        card_id= self.request.GET.get("lang")
        if card_id:
            obj= obj.filter(project_id=card_id)[0]
        comment = Comments.objects.filter(project = card_id)
        donations = Donation.objects.filter(project = card_id)

        context={
            'form': Comment_form,
            'project':obj,
            'com':comment,
            'don':donations
        }
        
        form = Comment_form(request.POST)
        if form.is_valid():
            comment = Comments()
            comment.author = request.user
            comment.text = form.cleaned_data['text']
            comment.project = obj
            comment.save()

        return render(request, 'detailedinfo.html', context)

class binnacle(View):
    def get(self,request):
      return render(request,'binnacle.html')

@method_decorator(login_required, name='dispatch')
class Home_view_employee(View):   
    def get(self, request):
        n_projects =Project.objects.count()
        n_donations =Donation.objects.count()
        n_convocatories =Convocatory.objects.count()
        n_clients = Client.objects.count()

        context={
            'active': 'dashboard',
            'n_projects':n_projects,
            'n_donations':n_donations,
            'n_convocatories':n_convocatories,
            'n_clients':n_clients,


        }
        return HttpResponse(render(request,'employee_views/employee_home_view.html',context))
    
    
class Employee_clients(View):   
    def get(self, request):
        context={
            'active': 'clients',
        }
        return HttpResponse(render(request,'clients_ehome.html',context))
    
class Employee_tools(View):   
    def get(self, request):
        employees = Employee.objects.all()

        context={
            'active': 'tools',
            'user':request.user,
            'employees':employees,
        }
        return HttpResponse(render(request,'tools_ehome.html',context))
    
class Gallery(View):
     def get(self,request):
        obj = Project.objects.all()
        category_id= self.request.GET.get("lang")
        if category_id:
            obj= obj.filter(category = category_id)
        return HttpResponse(render(request,'gallery.html',{'card':obj}))
     


class Employee_tools(View):   
    def get(self, request):
        employees = Employee.objects.all()
        context={
            'active': 'tools',
            'user':request.user,
            'employees':employees,
        }
        return HttpResponse(render(request,'employee_views/tools_ehome.html',context))

#Employee CRUD
@method_decorator(login_required, name='dispatch')
class Save_employee(View):
    def get(self,request):
        context={
            'title' : 'Guardar empleado',
            'active': 'tools',
            'form': Employee_register_form(),
        }
        return HttpResponse(render(request,'employee_views/crud_employee_ehome.html',context))
    
    def post(self, request):
        form = Employee_register_form(request.POST,request.FILES)
        if form.is_valid():

            user = User()
            user.username = form.cleaned_data['username']
            user.password = form.cleaned_data['password']
            user.is_client = False  
            user.is_employee = True  
            user.save()
            
            employee = Employee.objects.create(
                user=user,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                birth_date=form.cleaned_data['birth_date'],
                img=form.cleaned_data['img']    
            )

            order = form.save(commit=False) 
            order.user = user 
            order.save() 

            return redirect('core:etools')
        
        context = {
            'title': 'Guardar Empleados',
            'active': 'tools',
            'form': form,
        }
        return render(request, 'employee_views/crud_employee_ehome.html', context)
    
class Delete_employe(View):
    def delete_employee(request,username):
        user = User.objects.get(username=username)
        user.delete()
        return redirect('core:etools')
    
class Change_employee_password(View):
    def get(self,request,username):


        context={
            'user':username,
            'form':Employee_change_password(),

core/templates/base.html
<!doctype html>
{% load static %}

<html lang="en" style="height: 100%;">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Knowledge Projects</title>

  <link rel="stylesheet" href="{% static 'navbar.css'%}">
  <link rel="stylesheet" href="{% static 'toggler.css'%}">
  <link rel="stylesheet" href="{% static 'base.css'%}">
  <link rel="stylesheet" href="{% static 'spacing.css' %}">

  {% block htmlhead %}

  {% endblock htmlhead %}
</head>

<body style="height: 100%;display: flex;flex-direction: column;">
  <nav id="navbar">
    <!-- <img src="logo-db.png" alt="" width="55"> -->
    <span class="menu-icon" id="toggler">
      <input id="inn" class="menu-icon__cheeckbox" type="checkbox" />
      <div>
        <span></span>
        <span></span>
      </div>
    </span>

    <div id="nav-left">
      <a href={% url 'core:home' %}>Home</a>
      <a href={% url 'core:gallery' %}>Galería</a>
      <a href={% url 'core:categories' %}>Categorías</a>
      <a href={% url 'core:suggestions' %}>Sugerir Proyecto</a>
    </div>

    <div id="nav-right">
      {% if request.user.username == '' %}
      <a href={% url 'auth:register' %}>Registrarse</a>
      <a href={% url 'auth:login' %}>Iniciar sesión</a>
      {% else %}
      <a href="#">Hola, {{request.user.username}}</a>
      <a href={% url 'auth:logout' %}>Cerrar sesion</a>
      {% endif %}
    </div>

    <section class="dropdown">
      <ul>
        <li><a href={% url 'core:home' %}>Home</a></li>
        <li><a href={% url 'core:gallery' %}>Galería</a></li>
        <li><a href={% url 'core:categories' %}>Categorías</a></li>
        <li><a href={% url 'core:suggestions' %}>Sugerir Proyecto</a></li>
      </ul>
    </section>
  </nav>

  <div id="body-container" style="flex: 1 0 auto;  margin-bottom: 4rem;">
    {% block content%}

    {% endblock %}
    <script src="{% static 'navbar_script.js'%}"></script>
  </div>
  <footer>
    <div class="footer-content">
        <h3>Knowledge projects</h3>

        <a style="margin-bottom: 2rem;" href={% url 'core:employee_home' %}>Portal de administrador</a>
    </div>
    <div class="footer-bottom">
        <p>copyright &copy;2023 Structum. designed by <span>Grupo 1</span></p>
    </div>
  </footer>
</html>

core/templates/clients_ehome.html
{% extends "layouts/core/base_employee_view.html" %}
{% block content%}
<h1>Clientes</h1>
{% endblock %}

core/templates/detailedinfo.html
{% extends 'base.html' %}

{% load static %}

{% block htmlhead %}
<link rel="stylesheet" href="{% static 'gallery_style.css'%}">
<link rel="stylesheet" href="{% static 'carousel.css' %}">
{% endblock %}


{% block content %}
<section class="columns is-multiline" style="justify-content: center;">
  <div class="column is-3">
    <div class="mb-05">
      <h2 class="title is-family-primary mb1">{{project.project_name}}</h2>
      <span class="tag is-medium mb-05">{{project.category.category_name}}</span>
    </div>
    <p class="has-text-weight-medium mb-05">
      Presupuesto USD ${{project.budget}}
      <br>
      Progreso (implementación) 50%
    </p>
    <progress style="width: 80%;" class="progress is-primary" value="30" max="100">25%</progress>
  </div>

  <div class="column is-6">
    <div class="mb1">
      <h4 class="title is-family-primary mb-05">Descripción</h4>
      <p class="mb1">{{project.project_description}}</p>
    </div>

    <div class="mySlides mb2" style="display: block;">
      <div class="numbertext">1 / 3</div>
      <img src="{{project.img.url}}" style="width:100%">
    </div>

    <div class="mb1">
      <h4 class="title is-family-primary mb-05">Meta</h4>
      <p>{{project.goal}}</p>
    </div>

    <div class="mb1">
      <h4 class="title is-family-primary mb-05">Plan de trabajo</h4>
      <p>{{project.work_plan}}</p>
    </div>

    <div class="mb1">
      <h4 class="title is-family-primary mb-05">Alcance</h4>
      <p>{{project.scope}}</p>
    </div>

    <div class="mb1">
      <h4 class="title is-family-primary mb-05">Resultados</h4>
      <p>{{project.result}}</p>
    </div>

    <div class="flip-btn mb2">
      {% if not don %}
      <a class="button is-primary" href="{% url 'core:donation' project.project_id %}">Donar</a>
      {% endif %}

      {% if conv %}
      <a class="button is-secondary"
        href="{% url 'core:convocatory' %}?lang={{project.project_id}}">Inscribirse</a>
      {% endif %}
    </div>

    <div class="mb2">
      <h4 class="title is-family-primary mb1">Donante</h4>
      <div class="col" style="gap: 1rem;">
        {% if not don %}
          <p>Este proyecto no ha recibido donaciones</p>
        {% else %}
          {%for d in don%}
          <div class="box is-raised" style="width: 20rem; height: fit-content;">
            <div style="display: flex; flex-direction: row;">
              <p class="has-text-weight-semibold">{{d.user}}</p>
            </div>
            <p style="word-wrap: break-word;">
              Donó ${{d.amount}}
            </p>
          </div>
        {%endfor%}
        {% endif %}

      </div>
    </div>

    <form method="post" class="mb2">
      {% csrf_token %}
      <h4 class="title is-family-primary mb1">Ingresa un comentario</h4>

      <div class="form-group">
        <label for="{{ form.text.id_for_label }}"></label>
        <textarea name="text" class="textarea mb1" rows="2" placeholder="Comentario" maxlength="150"></textarea>
      </div>

      <button type="submit" class="button is-secondary is-small">Comentar</button>
    </form>

    <h4 class="title is-family-primary mb1">Comentarios</h4>
    <div class="col" style="gap: 1rem;">
      {% if not com %}
        <p>Aún no hay comentarios</p>
      {% else %}
        {%for c in com%}
        <div class="box is-raised" style="width: 20rem; height: fit-content;">
          <div style="display: flex; flex-direction: row;">
            <p class="has-text-weight-semibold">{{c.author.username}}</p>
            <p> - {{c.date}}</p>
          </div>
          <p style="word-wrap: break-word;">
            {{c.text}}
          </p>
        </div>
        {%endfor%}
      {% endif %}
    </div>
  </div>

</section>

{% endblock %}

core/templates/employee_home.html
{% extends "base.html" %}
{% block content%}
    
{% endblock %}

core/templates/home_view.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'base.css'%}">
    <link rel="stylesheet" href="{% static 'navbar.css'%}">
    <link rel="stylesheet" href="{% static 'toggler.css'%}">
    <link rel="stylesheet" href="{% static 'home_view_style.css'%}">

<body>
    <nav id="navbar">
        <!-- <img src="logo-db.png" alt="" width="55"> -->
        <span class="menu-icon" id="toggler">
            <input id="inn" class="menu-icon__cheeckbox" type="checkbox" />
            <div>
                <span></span>
                <span></span>
            </div>
        </span>

        <div id="nav-left">
            <a href={% url 'core:home' %}>Home</a>
            <a href={% url 'core:gallery' %}>Galería</a>
            <a href={% url 'core:categories' %}>Categorías</a>
            <a href={% url 'core:suggestions' %}>Sugerir Proyecto</a>
        </div>

        <div id="nav-right">
            {% if username == None %}
            <a href={% url 'auth:register' %}>Registrarse</a>
            <a href={% url 'auth:login' %}>Iniciar sesión</a>
            {% else %}
            <a href="#">{{username}}</a>
            <a href={% url 'auth:logout' %}>Cerrar sesion</a>
            {% endif %}
        </div>

        <section class="dropdown">
            <ul>
                <li><a href={% url 'core:home' %}>Home</a></li>
                <li><a href={% url 'core:gallery' %}>Galería</a></li>
                <li><a href={% url 'core:categories' %}>Categorías</a></li>
                <li> <a href={% url 'core:suggestions' %}>Sugerir Proyecto</a></li>
            </ul>
        </section>
    </nav>

    <div id="home-container">
        <div id="hero">
            <div id="hero-info">
                <div id="h1-p">
                    <h1 class="title is-family-primary">
                        Dona y cambia<br>al mundo
                    </h1>

                <p style="font-size: 1.25rem;">Nuestra comunidad está comprometida con impulsar la <u
                            class="is-success">innovación</u> y el <u class="is-warning">progreso</u> </p>
                </div>

                <div id="buttons">
                    <button class="button is-primary is-medium">Dona ahora</button>
                    <button class="button is-secondary is-medium">
                        Conoce las convocatorias
                    </button>
                </div>
            </div>
            <div id="hero-picture">
                <img id="kid-vr" src="{% static 'hero-picture.png' %}" alt="Whoopsie">
                <div id="hero-decor"></div>
            </div>
        </div>
        <div id="introduction">
            <div id="intro-text">
                <div class="d-flex flex-row mb-4 align-items-center">
                    <img src="{% static 'founder.png'%}" class="me-4 class=" img-fluid alt="" width="80px">
                    <div id="epa" class="text-white">
                        <h4 class="title is-family-primary" style="color: white;">Andrés Valencia</h4>
                        <p>Director creativo</p>
                    </div>
                </div>
                <h3 class="title is-family-primary" style="color: white;">El mejor lugar para poner en marcha su proyecto</h3>
                <p class="text-white" style="font-size: 1.25rem;">
                    Knowledge Projects hace parte de DreamsBank. Nuestro objetivo es
                    contribuir a que el mundo funcione mejor y cambiar la vida de las personas a través
                    de la innovación tecnológica
                </p>
            </div>
            <img id="p-image" src="{% static 'projects.png'%}" alt="">
        </div>
        <footer>
            <div class="footer-content">
                <h3>Knowledge projects</h3>
        
                <a style="margin-bottom: 2rem;" href={% url 'core:employee_home' %}>Portal de administrador</a>
            </div>
            <div class="footer-bottom">
                <p>copyright &copy;2023 Structum. designed by <span>Grupo 1</span></p>
            </div>
          </footer>
        <script src="{% static 'navbar_script.js' %}"></script>
    </div>

</body>

</html>

core/templates/project.html
{% extends 'base.html' %}

{% load static %}

{% block htmlhead %}
<link rel="stylesheet" href="{% static 'gallery_style.css'%}">
<link rel="stylesheet" href="{% static 'carousel.css' %}">
{% endblock %}


{% block content %}
<section id="flip">
  <div class="flip-carousel">
    <script src="{% static 'carousel.js' %}"></script>
    <!-- Slideshow container -->
    <div class="slideshow-container">
      <!-- Full-width images with number and caption text -->
      <div class="mySlides fade" style="display: block;">
        <div class="numbertext">1 / 3</div>
        <img src="{{project.img.url}}" style="width:100%">
      </div>

      <div class="mySlides fade">
        <div class="numbertext">2 / 3</div>
        <img src="{{project.img.url}}" style="width:100%">
      </div>

      <div class="mySlides fade">
        <div class="numbertext">3 / 3</div>
        <img src="{{project.img.url}}" style="width:100%">
      </div>

      <!-- Next and previous buttons -->
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    </div>

    <div style="text-align:center">
      <span class="dot" onclick="currentSlide(1)"></span>
      <span class="dot" onclick="currentSlide(2)"></span>
      <span class="dot" onclick="currentSlide(3)"></span>
    </div>
  </div>
  <div id="info">
    <span class="tag is-medium mb-05">{{project.category.category_name}}</span>
    <h2 class="title is-family-primary mb1">{{project.project_name}}</h2>

    <p class="mb1">{{project.project_description}} <br> <a class="mb1 is-underlined is-regular"
        href="{% url 'core:detailedinfo' %}?lang={{project.project_id}}">Ver bitácora</a></p>

    <p class="has-text-weight-medium mb1">
      Presupuesto USD ${{project.budget}}
      <br>
      Progreso (implementación) 50%
    </p>

    <progress class="progress is-primary mb2" value="30" max="100">25%</progress>

    <div class="flip-btn">
      {% if not don %}
      <a class="button is-primary" href="{% url 'core:donation' project.project_id %}">Donar</a>
      {% endif %}

      {% if conv %}
      <a class="button is-secondary"
        href="{% url 'core:convocatory' %}?lang={{project.project_id}}">Inscribirse</a>
      {% endif %}

    </div>
  </div>
</section>

<section>
  {% if not related %}
  <div>
    <h3 class="title is-family-primary">
      No hay proyectos similares
    </h3>
  </div>
  {%else%}

  <section class="col">
    <h3 class="title is-family-primary mb1">
      Proyectos similares
    </h3>

    <div id="grid" style="justify-content: flex-start;">
      {%for x in related%}
      <div class="box is-raised">
        <img src="{{x.img.url}}" class="card-image mb-05">
        <div style="height: 12rem;">
          <div class="ex-v mb1">
            <span class="tag mb1">{{x.category.category_name}}</span>
            <h4 class="title is-family-primary" style="margin-bottom: 0.5rem !important;">{{x.project_name}}</h4>
            <p class="mb1 text-limiter">{{x.project_description}}</p>
          </div>
          <a class="button is-small is-primary" href="{% url 'core:project' %}?lang={{x.project_id}}">
            Conocer más
          </a>
        </div>
      </div>
      {%endfor%}
    </div>

  </section>

  {% endif %}
</section>
{% endblock %}